CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS goal (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  goal_title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS goal_details (
  id SERIAL PRIMARY KEY,
  goal_id INT NOT NULL REFERENCES goal(id) ON DELETE CASCADE,
  update_text VARCHAR(255)
);